handle multiple USB devices to be mounted

diff --git a/nya b/nya
--- a/nya
+++ b/nya
@@ -1,17 +1,18 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Copyright 2018 (c) Capuccino <enra@sayonika.moe>
 #
 #
 # Feel free to improve this script on GitHub
 
+# I ran out of ideas here so feel free to do some weird lettering shit that matches this more
 while getopts ":i:g:u:l:x:" o; do
     case "${o}" in
         i)
             image=${OPTARG}
             ;;
         u)
-            usb=${OPTARG}
+            multi+=${OPTARG}
             ;;
         g)  
             gpu_vendor_id=${OPTARG}
@@ -25,6 +26,7 @@ while getopts ":i:g:u:l:x:" o; do
         *)
             echo "Usage: $0 -i <image_file> -u <usb_vendor_id> -g <gpu_vendor_id> -l <gpu_model_id> -x <gpu_pci_id>"
             echo "You can grab the USB vendor ID from lsusb and for the GPU Vendor, GPU Model, and the Bus ID, use lspci."
+            exit 1;
             ;;
     esac
 done
@@ -33,6 +35,7 @@ shift $((OPTIND-1))
 if [ -z "${gpu_model_id}" ] || [ -z "${gpu_vendor_id}" ] || [ -z "${usb}" ] || [ -z "${image}" ] || [ -z "${gpu_pci_id}" ]; then
     echo "Usage: $0 -i <image_file> -u <usb_vendor_id> -g <gpu_vendor_id> -l <gpu_model_id> -x <gpu_pci_id>"
     echo "You can grab the USB vendor ID from lsusb and for the GPU Vendor, GPU Model, and the Bus ID, use lspci."
+    exit 1;
 fi
 
 
@@ -42,10 +45,10 @@ arch="$(uname -p)"
 export qemu_target_arch=
 
 case $arch in
-  x86_64\*) qemu_target_arch="qemu-system-x86_64" ;;
-  i386\*) qemu_target_arch="qemu-system-i385" ;;
-  arm\*) qemu_target_arch="qemu-system-arm" ;;
-  ppc64el\*) qemu_target_arch="qemu-system-powerpc" ;;
+  x86_64) qemu_target_arch="qemu-system-x86_64" ;;
+  i386) qemu_target_arch="qemu-system-i385" ;;
+  arm) qemu_target_arch="qemu-system-arm" ;;
+  ppc64el) qemu_target_arch="qemu-system-powerpc" ;;
   *) echo "Unsupported arch"; exit 1 ;;
 esac
 
@@ -56,11 +59,8 @@ if [ -z "$(command -v $qemu_bin)" ]; then
   exit 1;
 fi
 
-if [ -z "$1" ]; then
-  echo "Error: you need to tell me what image should I mount."
-  exit 2;
-elif [ ! -f "$1" ]; then
-  echo "Error: Image does not exist."
+if [ ! -f "$image" ]; then
+  echo "Error: image does not exist"
   exit 2;
 fi
 
@@ -68,14 +68,8 @@ echo "Mounting Image $1."
 echo "If you ever encounter issues with this script, please report immediately so we know what we can do."
 sleep 3
 
-# Let's initialize some Controllers
-# we need to parse the following:
-# - GPU
-# - USB Host
-# 
-# The very reason for this is no one is gonna be assed to do lspci or don't know how to use it so we're gonna be
-# grabbing the PCI id for the VGA controller.
 
+# This is mostly required as QEMU/KVM will use the vfio drivers to do the passthrough
 
 echo "Enabling vfio drivers"
   sudo modprobe vfio
@@ -83,6 +77,9 @@ echo "Enabling vfio drivers"
   echo "0000:$gpu_pci_id" | sudo tee /sys/bus/pci/devices/0000:01:00.1/driver/unbind
   echo 1002 6739 | sudo tee /sys/bus/pci/drivers/vfio-pci/new_id
   echo 1002 aa88 | sudo tee /sys/bus/pci/drivers/vfio-pci/new_id 
+
+# If you're seeing this that means I got bored and I literally provided you a prebuilt SeaBIOS
+# Which I'm certain probably wouldn't be up to date.
 
 echo "Acquiring SeaBIOS."
 
@@ -99,18 +96,26 @@ echo "Acquiring SeaBIOS."
      qemu-img create -f qcow2 "$qemu_disk_img" 50g
  fi
 
+
+
 # TODO: get USB IDs properly.
 export QEMU_AUDIO_DRV=alsa QEMU_AUDIO_TIMER_PERIOD=0
-qemu-system-x86_64 \
+cmd="qemu-system-x86_64 \
     -enable-kvm -M q35 -m 1024 -cpu host -smp 4,sockets=1,cores=4,threads=1 \
     -cpu host,kvm=off \
     -bios /usr/share/qemu/bios.bin -vga none \
     -device ioh3420,bus=pcie.0,addr=1c.0,multifunction=on,port=1,chassis=1,id=root.1 \
     -device piix4-ide,bus=pcie.0,id=piix4-ide \
-    -device vfio-pci,host=01:00.0,bus=root.1,addr=00.0,multifunction=on,x-vga=on,romfile="$qemu_seabios_bin" \
+    -device vfio-pci,host=01:00.0,bus=root.1,addr=00.0,multifunction=on,x-vga=on,romfile=$qemu_seabios_bin \
     -device vfio-pci,host=01:00.1,bus=pcie.0 \
-    -usb -usbdevice host:"$usb" -usbdevice host:1d6b:0002 \
+    -usb -usbdevice host:$usb \
     -soundhw ac97 \
-    -drive file="$qemu_disk_img",id=disk,format=raw -device ide-hd,bus=piix4-ide.0,drive=disk \
-    -drive file="$image",id=isocd -device ide-cd,bus=piix4-ide.1,drive=isocd \
-;
+    -drive file=$qemu_disk_img,id=disk,format=raw -device ide-hd,bus=piix4-ide.0,drive=disk \
+    -drive file=$image,id=isocd -device ide-cd,bus=piix4-ide.1,drive=isocd \
+;"
+
+for val in "${multi[@]}"; do
+  echo "-usb -usbdevice host:$val \\" >> "$cmd";
+done
+
+exec "$cmd"
